"""시가총액 상위 미국 종목 하드코딩 리스트 (수동 큐레이션).

매년/분기마다 갱신. 현재(2026-05) 기준 상위 100.
출처: companiesmarketcap.com 등 공개 데이터 참조.

각 entry: (symbol, market, name) - market은 NASDAQ/NYSE.
KR과 달리 영문명만 있음 (한국어명은 NULL).
"""

US_TOP_100: list[tuple[str, str, str]] = [
    ("AAPL", "NASDAQ", "Apple Inc."),
    ("MSFT", "NASDAQ", "Microsoft Corporation"),
    ("NVDA", "NASDAQ", "NVIDIA Corporation"),
    ("GOOGL", "NASDAQ", "Alphabet Inc. Class A"),
    ("GOOG", "NASDAQ", "Alphabet Inc. Class C"),
    ("AMZN", "NASDAQ", "Amazon.com, Inc."),
    ("META", "NASDAQ", "Meta Platforms, Inc."),
    ("TSLA", "NASDAQ", "Tesla, Inc."),
    ("BRK-B", "NYSE", "Berkshire Hathaway Inc."),
    ("AVGO", "NASDAQ", "Broadcom Inc."),
    ("LLY", "NYSE", "Eli Lilly and Company"),
    ("JPM", "NYSE", "JPMorgan Chase & Co."),
    ("WMT", "NYSE", "Walmart Inc."),
    ("V", "NYSE", "Visa Inc."),
    ("XOM", "NYSE", "Exxon Mobil Corporation"),
    ("ORCL", "NYSE", "Oracle Corporation"),
    ("MA", "NYSE", "Mastercard Incorporated"),
    ("UNH", "NYSE", "UnitedHealth Group Incorporated"),
    ("COST", "NASDAQ", "Costco Wholesale Corporation"),
    ("HD", "NYSE", "The Home Depot, Inc."),
    ("PG", "NYSE", "The Procter & Gamble Company"),
    ("JNJ", "NYSE", "Johnson & Johnson"),
    ("BAC", "NYSE", "Bank of America Corporation"),
    ("ABBV", "NYSE", "AbbVie Inc."),
    ("NFLX", "NASDAQ", "Netflix, Inc."),
    ("CRM", "NYSE", "Salesforce, Inc."),
    ("CVX", "NYSE", "Chevron Corporation"),
    ("KO", "NYSE", "The Coca-Cola Company"),
    ("AMD", "NASDAQ", "Advanced Micro Devices, Inc."),
    ("MRK", "NYSE", "Merck & Co., Inc."),
    ("PEP", "NASDAQ", "PepsiCo, Inc."),
    ("TMO", "NYSE", "Thermo Fisher Scientific Inc."),
    ("LIN", "NASDAQ", "Linde plc"),
    ("ACN", "NYSE", "Accenture plc"),
    ("ADBE", "NASDAQ", "Adobe Inc."),
    ("WFC", "NYSE", "Wells Fargo & Company"),
    ("MCD", "NYSE", "McDonald's Corporation"),
    ("DIS", "NYSE", "The Walt Disney Company"),
    ("CSCO", "NASDAQ", "Cisco Systems, Inc."),
    ("ABT", "NYSE", "Abbott Laboratories"),
    ("DHR", "NYSE", "Danaher Corporation"),
    ("IBM", "NYSE", "International Business Machines Corporation"),
    ("GE", "NYSE", "General Electric Company"),
    ("QCOM", "NASDAQ", "QUALCOMM Incorporated"),
    ("INTU", "NASDAQ", "Intuit Inc."),
    ("AMGN", "NASDAQ", "Amgen Inc."),
    ("AXP", "NYSE", "American Express Company"),
    ("TXN", "NASDAQ", "Texas Instruments Incorporated"),
    ("VZ", "NYSE", "Verizon Communications Inc."),
    ("NOW", "NYSE", "ServiceNow, Inc."),
    ("PM", "NYSE", "Philip Morris International Inc."),
    ("RTX", "NYSE", "RTX Corporation"),
    ("ISRG", "NASDAQ", "Intuitive Surgical, Inc."),
    ("MS", "NYSE", "Morgan Stanley"),
    ("BX", "NYSE", "Blackstone Inc."),
    ("CAT", "NYSE", "Caterpillar Inc."),
    ("GS", "NYSE", "The Goldman Sachs Group, Inc."),
    ("PFE", "NYSE", "Pfizer Inc."),
    ("T", "NYSE", "AT&T Inc."),
    ("PGR", "NYSE", "The Progressive Corporation"),
    ("BKNG", "NASDAQ", "Booking Holdings Inc."),
    ("NEE", "NYSE", "NextEra Energy, Inc."),
    ("TMUS", "NASDAQ", "T-Mobile US, Inc."),
    ("C", "NYSE", "Citigroup Inc."),
    ("SCHW", "NYSE", "The Charles Schwab Corporation"),
    ("SPGI", "NYSE", "S&P Global Inc."),
    ("BLK", "NYSE", "BlackRock, Inc."),
    ("HON", "NASDAQ", "Honeywell International Inc."),
    ("ETN", "NYSE", "Eaton Corporation plc"),
    ("BSX", "NYSE", "Boston Scientific Corporation"),
    ("DE", "NYSE", "Deere & Company"),
    ("ELV", "NYSE", "Elevance Health, Inc."),
    ("GILD", "NASDAQ", "Gilead Sciences, Inc."),
    ("BA", "NYSE", "The Boeing Company"),
    ("CB", "NYSE", "Chubb Limited"),
    ("VRTX", "NASDAQ", "Vertex Pharmaceuticals Incorporated"),
    ("LMT", "NYSE", "Lockheed Martin Corporation"),
    ("PANW", "NASDAQ", "Palo Alto Networks, Inc."),
    ("ADP", "NASDAQ", "Automatic Data Processing, Inc."),
    ("ANET", "NYSE", "Arista Networks, Inc."),
    ("MDLZ", "NASDAQ", "Mondelez International, Inc."),
    ("REGN", "NASDAQ", "Regeneron Pharmaceuticals, Inc."),
    ("MMC", "NYSE", "Marsh & McLennan Companies, Inc."),
    ("SYK", "NYSE", "Stryker Corporation"),
    ("SO", "NYSE", "The Southern Company"),
    ("ICE", "NYSE", "Intercontinental Exchange, Inc."),
    ("PLD", "NYSE", "Prologis, Inc."),
    ("MO", "NYSE", "Altria Group, Inc."),
    ("CMCSA", "NASDAQ", "Comcast Corporation"),
    ("AMT", "NYSE", "American Tower Corporation"),
    ("ZTS", "NYSE", "Zoetis Inc."),
    ("DUK", "NYSE", "Duke Energy Corporation"),
    ("FI", "NYSE", "Fiserv, Inc."),
    ("INTC", "NASDAQ", "Intel Corporation"),
    ("CME", "NASDAQ", "CME Group Inc."),
    ("EQIX", "NASDAQ", "Equinix, Inc."),
    ("TJX", "NYSE", "The TJX Companies, Inc."),
    ("EOG", "NYSE", "EOG Resources, Inc."),
    ("AON", "NYSE", "Aon plc"),
    ("SHW", "NYSE", "The Sherwin-Williams Company"),
]

# 누락 방지를 위한 모듈 로드 시 검증
assert len(US_TOP_100) == 100, f"US_TOP_100 should have exactly 100 entries, got {len(US_TOP_100)}"
